version: "3.1"
services:

    gitea:
        image: gitea/gitea:1.13
        restart: always
        volumes:
            - .:/application
            - /mnt/user/appdata/gitea:/data
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.gitea.rule=Host(`git.rauhala.dev`)"
            - "traefik.http.services.gitea.loadbalancer.server.port=3000"
            - "traefik.http.routers.gitea.entrypoints=https"
            - "traefik.http.routers.gitea.tls=true"
            - "traefik.http.routers.gitea.tls.certresolver=http"
            - "traefik.http.routers.gitea.tls.domains[0].main=rauhala.dev"
            - "traefik.http.routers.gitea.tls.domains[0].sans=*.rauhala.dev"

networks:
    default:
        external:
            name: web
