version: "3.1"
services:

    adguardhome:
        image: adguard/adguardhome
        restart: always
        volumes:
            - ./data/work:/opt/adguardhome/work
            - ./data/conf:/opt/adguardhome/conf
        ports:
            - 53:53/tcp
            - 53:53/udp
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.adguardhome.rule=Host(`dns.mirorauhala.fi`)"
            - "traefik.http.services.adguardhome.loadbalancer.server.port=80"
            - "traefik.http.routers.adguardhome.entrypoints=https"
            - "traefik.http.routers.adguardhome.tls=true"
            - "traefik.http.routers.adguardhome.tls.certresolver=http"
            - "traefik.http.routers.adguardhome.tls.domains[0].main=mirorauhala.fi"
            - "traefik.http.routers.adguardhome.tls.domains[0].sans=*.mirorauhala.fi"

networks:
    default:
        external:
            name: web
